// Only the latest bot-owned private draft after the latest public message is offered.
// Prefix alone never proves that a message was generated by the assigned bot.
export const AI_DRAFT_PREFIX = '✦ AI が下書きを作成しました\n\n';

export function latestToybacoAiDraft(messages) {
  if (!Array.isArray(messages)) return null;
  for (let index = messages.length - 1; index >= 0; index -= 1) {
    const message = messages[index];
    if (!message) continue;
    if (!message.private && [0, 1, 'incoming', 'outgoing'].includes(message.message_type)) return null;
    if (message.private !== true || message.sender?.type !== 'agent_bot' ||
        ![1, 'outgoing'].includes(message.message_type) ||
        typeof message.content !== 'string' || !message.content.startsWith(AI_DRAFT_PREFIX)) continue;
    const content = message.content.slice(AI_DRAFT_PREFIX.length).trim();
    return content ? { id: message.id, content } : null;
  }
  return null;
}
