# frozen_string_literal: true

require_relative 'toybaco_growth_posting_renewal_runtime_test'
require_relative 'toybaco_growth_renewal_dispatch_posting_cases'
ToybacoGrowthRenewalTransitionRuntimeTest.prepend(ToybacoGrowthRenewalDispatchPostingCases)
