export default [
  {
    id: 1,
    title: 'カスタムドメイン用SSL証明書を取得する方法',
    status: 'draft',
    updatedAt: 1729205669,
    author: { availableName: '佐藤' },
    category: {
      slug: 'configuration',
      icon: '📦',
      name: '設定・構成',
    },
    views: 3400,
  },
  {
    id: 2,
    title: '最初のヘルプセンターポータルを設定する',
    status: 'published',
    updatedAt: 1729205669,
    author: { availableName: '鈴木' },
    category: { slug: 'onboarding', icon: '🧑‍🍳', name: '導入ガイド' },
    views: 400,
  },
  {
    id: 3,
    title: 'ヘルプセンターコンテンツ整理のベストプラクティス',
    status: 'archived',
    updatedAt: 1729205669,
    author: { availableName: '高橋' },
    category: { slug: 'best-practices', icon: '⛺️', name: 'ベストプラクティス' },
    views: 400,
  },
  {
    id: 4,
    title: 'ヘルプセンターの外観をカスタマイズする',
    status: 'draft',
    updatedAt: 1729205669,
    author: { availableName: '田中' },
    category: { slug: 'design', icon: '🎨', name: 'デザイン' },
    views: 400,
  },
  {
    id: 5,
    title: 'ヘルプセンターを外部ツールと連携する',
    status: 'published',
    updatedAt: 1729205669,
    author: { availableName: '伊藤' },
    category: {
      slug: 'integrations',
      icon: '🔗',
      name: '連携',
    },
    views: 2800,
  },
  {
    id: 6,
    title: 'ヘルプセンターのユーザー権限を管理する',
    status: 'draft',
    updatedAt: 1729205669,
    author: { availableName: '渡辺' },
    category: {
      slug: 'administration',
      icon: '🔐',
      name: '管理',
    },
    views: 1200,
  },
  {
    id: 7,
    title: 'FAQセクションを作成・管理する',
    status: 'published',
    updatedAt: 1729205669,
    author: { availableName: '山本' },
    category: {
      slug: 'content-management',
      icon: '📝',
      name: 'コンテンツ管理',
    },
    views: 5600,
  },
  {
    id: 8,
    title: 'ヘルプセンターに検索機能を導入する',
    status: 'archived',
    updatedAt: 1729205669,
    author: { availableName: '中村' },
    category: {
      slug: 'features',
      icon: '🔍',
      name: '機能',
    },
    views: 1800,
  },
  {
    id: 9,
    title: 'ヘルプセンターの利用状況を分析する',
    status: 'published',
    updatedAt: 1729205669,
    author: { availableName: '小林' },
    category: {
      slug: 'analytics',
      icon: '📊',
      name: '分析',
    },
    views: 3200,
  },
  {
    id: 10,
    title: 'ヘルプセンターを多言語対応にする',
    status: 'draft',
    updatedAt: 1729205669,
    author: { availableName: '加藤' },
    category: {
      slug: 'localization',
      icon: '🌍',
      name: '多言語対応',
    },
    views: 900,
  },
  {
    id: 11,
    title: '製品向けインタラクティブチュートリアルを作成する',
    status: 'published',
    updatedAt: 1729205669,
    author: { availableName: '吉田' },
    category: {
      slug: 'education',
      icon: '🎓',
      name: '学習ガイド',
    },
    views: 4100,
  },
  {
    id: 12,
    title: 'ヘルプセンターにフィードバック機能を導入する',
    status: 'draft',
    updatedAt: 1729205669,
    author: { availableName: '山田' },
    category: {
      slug: 'user-engagement',
      icon: '💬',
      name: 'ユーザーエンゲージメント',
    },
    views: 750,
  },
  {
    id: 13,
    title: 'ヘルプセンターコンテンツをSEO最適化する',
    status: 'published',
    updatedAt: 1729205669,
    author: { availableName: '佐々木' },
    category: {
      slug: 'seo',
      icon: '🚀',
      name: 'SEO対策',
    },
    views: 2900,
  },
  {
    id: 14,
    title: '社内チーム向けナレッジベースを作成する',
    status: 'archived',
    updatedAt: 1729205669,
    author: { availableName: '山口' },
    category: {
      slug: 'internal-resources',
      icon: '🏢',
      name: '社内資料',
    },
    views: 1500,
  },
];
